#!/bin/bash
# install-named-tunnel.sh — Switch to Cloudflare named tunnel (pocket-lab)
# Generated by Perplexity Computer at 2026-04-24T22:22:25Z
set -e

TUNNEL_ID="8132ec84-8724-4be1-a588-9e62ea6c3562"
TUNNEL_TOKEN="eyJhIjoiZjdjOGUxN2U0N2IyYmE2MTIyNDg1MGQ3YmI5ODkyN2YiLCJ0IjoiODEzMmVjODQtODcyNC00YmUxLWE1ODgtOWU2MmVhNmMzNTYyIiwicyI6Ik9EYzFPR1JrWTJSaFl6TmxZV1JrWVdJMlpUSTRNalUxTkdNME5XVm1NVE0wWlRsaE1tWTFabVE0WTJZNE5tVXhOakZpTTJSak1tUXhaR016TkdVNVpBPT0ifQ=="
CF_DIR="${HOME}/.cloudflared"
SERVICE_DST="${HOME}/.config/systemd/user/cloudflared-tunnel.service"
REPO="${HOME}/pocket-lab-v2-6"

echo "╔══════════════════════════════════════════════════════╗"
echo "║  Pocket Lab — Install Named Cloudflare Tunnel       ║"
echo "║  tunnel: pocket-lab (8132ec84...)          ║"
echo "╚══════════════════════════════════════════════════════╝"

# 1. Write credentials
mkdir -p "$CF_DIR"
cat > "$CF_DIR/8132ec84-8724-4be1-a588-9e62ea6c3562.json" << 'CREDS'
{
  "AccountTag": "f7c8e17e47b2ba61224850d7bb98927f",
  "TunnelID": "8132ec84-8724-4be1-a588-9e62ea6c3562",
  "TunnelName": "pocket-lab",
  "TunnelSecret": "ODc1OGRkY2RhYzNlYWRkYWI2ZTI4MjU1NGM0NWVmMTM0ZTlhMmY1ZmQ4Y2Y4NmUxNjFiM2RjMmQxZGMzNGU5ZA=="
}
CREDS
echo "[1/4] Credentials written to $CF_DIR/8132ec84-8724-4be1-a588-9e62ea6c3562.json"

# 2. Write config.yml
cat > "$CF_DIR/config.yml" << CFGYML
tunnel: 8132ec84-8724-4be1-a588-9e62ea6c3562
credentials-file: ${HOME}/.cloudflared/8132ec84-8724-4be1-a588-9e62ea6c3562.json
ingress:
  - service: ssh://localhost:22
CFGYML
echo "[2/4] Config written to $CF_DIR/config.yml"

# 3. Update systemd service to use token (simplest, most reliable)
mkdir -p "${HOME}/.config/systemd/user"
cat > "$SERVICE_DST" << 'SVC'
[Unit]
Description=Pocket Lab — cloudflared named tunnel (pocket-lab)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=PATH=/home/newuser/.local/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=/bin/sh -c 'exec "${HOME}/.local/bin/cloudflared" tunnel --no-autoupdate run --token eyJhIjoiZjdjOGUxN2U0N2IyYmE2MTIyNDg1MGQ3YmI5ODkyN2YiLCJ0IjoiODEzMmVjODQtODcyNC00YmUxLWE1ODgtOWU2MmVhNmMzNTYyIiwicyI6Ik9EYzFPR1JrWTJSaFl6TmxZV1JrWVdJMlpUSTRNalUxTkdNME5XVm1NVE0wWlRsaE1tWTFabVE0WTJZNE5tVXhOakZpTTJSak1tUXhaR016TkdVNVpBPT0ifQ=='
Restart=always
RestartSec=5
NoNewPrivileges=true

[Install]
WantedBy=default.target
SVC

# Fix HOME path in service
sed -i "s|/home/newuser|/home/$(whoami)|g" "$SERVICE_DST" 2>/dev/null || true
echo "[3/4] Systemd service updated"

# 4. Restart service
systemctl --user daemon-reload
systemctl --user stop cloudflared-tunnel.service 2>/dev/null || true
systemctl --user enable cloudflared-tunnel.service
systemctl --user start cloudflared-tunnel.service
sleep 4
echo "[4/4] Service restarted"

echo ""
echo "Status:"
systemctl --user status cloudflared-tunnel.service --no-pager -l | head -20
echo ""
echo "Tunnel is live — permanent hostname:"
echo "  8132ec84-8724-4be1-a588-9e62ea6c3562.cfargotunnel.com"
