#!/bin/bash
# ============================================================
# umaf-setup.sh — Automated Smokeless UMAF USB Preparation
# Generated by Perplexity Computer 2026-04-25
#
# What this does:
#   1. Downloads UMAF_BETA.zip from GitHub
#   2. Detects your USB drive
#   3. Formats it FAT32
#   4. Extracts UMAF onto it
#   5. Adds a one-time EFI boot entry so it boots from USB next restart
#
# Usage:
#   bash ~/pocket-lab-v2-6/linux/umaf-setup.sh [/dev/sdX]
#   (if USB device not specified, script will auto-detect)
#
# After running:
#   sudo reboot
#   → Machine boots into UMAF
#   → Device Manager → AMD CBS → CPU Common Options → SMT Control → Enable
#   → Escape → Save → Continue → boots back to Ubuntu
# ============================================================
set -e

UMAF_URL="https://github.com/DavidS95/Smokeless_UMAF/raw/main/UMAF_BETA.zip"
UMAF_ZIP="/tmp/UMAF_BETA.zip"
MOUNT_POINT="/tmp/umaf-usb"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "╔══════════════════════════════════════════════════════╗"
echo "║   Pocket Lab — Smokeless UMAF USB Setup             ║"
echo "║   Target: Enable SMT on Ryzen 7 4700U               ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Detect USB drive ─────────────────────────────────
echo "[1/5] Detecting USB drive..."
if [ -n "$1" ]; then
    USB_DEV="$1"
    echo "  Using specified device: $USB_DEV"
else
    # Auto-detect USB block device
    USB_DEV=$(lsblk -o NAME,TRAN,TYPE --json 2>/dev/null | python3 -c "
import sys,json
data = json.load(sys.stdin)
for d in data.get('blockdevices',[]):
    if d.get('tran') == 'usb' and d.get('type') == 'disk':
        print('/dev/' + d['name'])
        break
" 2>/dev/null || echo "")
fi

if [ -z "$USB_DEV" ]; then
    echo ""
    echo "   No USB drive detected."
    echo "  Please plug in a USB drive and re-run, or specify it:"
    echo "    bash ~/pocket-lab-v2-6/linux/umaf-setup.sh /dev/sdX"
    echo ""
    echo "  Available devices:"
    lsblk -o NAME,SIZE,TRAN,LABEL,TYPE | grep -v loop
    exit 1
fi

# Safety check — make sure it's not the NVMe
if echo "$USB_DEV" | grep -q "nvme"; then
    echo "   ERROR: $USB_DEV looks like your NVMe SSD — refusing to format it!"
    echo "  Please specify your USB drive explicitly."
    exit 1
fi

USB_SIZE=$(lsblk -o NAME,SIZE "$USB_DEV" | grep "$(basename $USB_DEV) " | awk '{print $2}')
echo "  Found USB: $USB_DEV ($USB_SIZE)"
echo ""
echo "    WARNING: $USB_DEV ($USB_SIZE) will be FORMATTED (all data erased)"
read -p "  Type YES to continue: " CONFIRM
if [ "$CONFIRM" != "YES" ]; then
    echo "  Aborted."
    exit 0
fi

# ── Step 2: Download UMAF ────────────────────────────────────
echo ""
echo "[2/5] Downloading UMAF_BETA.zip..."
if [ -f "$UMAF_ZIP" ]; then
    echo "  Already downloaded: $UMAF_ZIP"
else
    curl -fL --progress-bar "$UMAF_URL" -o "$UMAF_ZIP"
    echo "  Downloaded: $(du -h $UMAF_ZIP | cut -f1)"
fi

# ── Step 3: Unmount + Format USB FAT32 ──────────────────────
echo ""
echo "[3/5] Formatting $USB_DEV as FAT32..."

# Unmount any partitions
for part in $(lsblk -ln -o NAME "$USB_DEV" | tail -n +2); do
    sudo umount "/dev/$part" 2>/dev/null && echo "  Unmounted /dev/$part" || true
done

# Wipe and create fresh partition table
sudo parted "$USB_DEV" --script mklabel msdos
sudo parted "$USB_DEV" --script mkpart primary fat32 1MiB 100%
sudo parted "$USB_DEV" --script set 1 boot on

# Wait for kernel to see new partition
sleep 2
USB_PART="${USB_DEV}1"
# Handle nvme-style naming (shouldn't be USB but just in case)
[ -b "${USB_DEV}p1" ] && USB_PART="${USB_DEV}p1"

# Format FAT32
sudo mkfs.fat -F32 -n "UMAF" "$USB_PART"
echo "  Formatted: $USB_PART as FAT32"

# ── Step 4: Mount + Extract UMAF ────────────────────────────
echo ""
echo "[4/5] Extracting UMAF to USB..."
mkdir -p "$MOUNT_POINT"
sudo mount "$USB_PART" "$MOUNT_POINT"

# Extract zip to USB root
sudo unzip -o "$UMAF_ZIP" -d "$MOUNT_POINT/" 2>&1 | tail -5

# Verify EFI structure exists
if [ ! -d "$MOUNT_POINT/EFI" ]; then
    echo "    No EFI folder found in zip root — checking subdirs..."
    SUBDIR=$(ls "$MOUNT_POINT" | head -1)
    if [ -d "$MOUNT_POINT/$SUBDIR/EFI" ]; then
        echo "  Found EFI in $SUBDIR/ — moving to root..."
        sudo mv "$MOUNT_POINT/$SUBDIR/"* "$MOUNT_POINT/"
        sudo rmdir "$MOUNT_POINT/$SUBDIR" 2>/dev/null || true
    fi
fi

echo "  USB contents:"
ls -la "$MOUNT_POINT/"

sudo umount "$MOUNT_POINT"
echo "  Unmounted USB"

# ── Step 5: Add one-time EFI boot entry ─────────────────────
echo ""
echo "[5/5] Adding one-time EFI boot entry for UMAF USB..."

# Find the EFI bootloader on the USB
sudo mount "$USB_PART" "$MOUNT_POINT"
EFI_PATH=$(find "$MOUNT_POINT/EFI" -name "*.efi" 2>/dev/null | head -1 | sed "s|$MOUNT_POINT||")
sudo umount "$MOUNT_POINT"

if [ -z "$EFI_PATH" ]; then
    # Common UMAF path
    EFI_PATH="/EFI/BOOT/BOOTX64.EFI"
fi

echo "  EFI loader path: $EFI_PATH"

# Get USB partition disk identifier
USB_PART_NUM=$(echo "$USB_PART" | grep -o '[0-9]*$')

# Add as one-time boot entry (BootNext — runs once then reverts)
BOOT_ENTRY=$(sudo efibootmgr --create \
    --disk "$USB_DEV" \
    --part "$USB_PART_NUM" \
    --label "Smokeless UMAF" \
    --loader "$EFI_PATH" \
    2>/dev/null | grep "Boot[0-9]" | grep -o 'Boot[0-9A-F]*' | head -1 || echo "")

if [ -n "$BOOT_ENTRY" ]; then
    BOOT_NUM=$(echo "$BOOT_ENTRY" | sed 's/Boot//')
    sudo efibootmgr --bootnext "$BOOT_NUM" 2>/dev/null
    echo "  Boot entry created: $BOOT_ENTRY (set as BootNext)"
    echo "  Machine will boot UMAF once, then return to normal Ubuntu boot"
else
    echo "  Could not auto-add EFI entry — you'll need to select USB manually in BIOS boot menu"
    echo "  Press F2 at boot → Boot menu → select 'UMAF' or USB entry"
fi

# ── Done ─────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  UMAF USB READY                                     ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  USB: $USB_DEV ($USB_SIZE)"
echo "║"
echo "║  Next steps:                                        ║"
echo "║  1. sudo reboot                                     ║"
echo "║  2. Machine boots into Smokeless UMAF               ║"
echo "║  3. Select: Device Manager                          ║"
echo "║  4. Select: AMD CBS                                 ║"
echo "║  5. Select: CPU Common Options                      ║"
echo "║  6. Find:   SMT Control → set to Enable             ║"
echo "║  7. Press Escape → Save → Continue                  ║"
echo "║  8. Ubuntu boots normally with SMT enabled          ║"
echo "║"
echo "║    ONLY change SMT Control — nothing else!        ║"
echo "║  Touching other settings can brick the laptop.      ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "Run: sudo reboot"
